services:
  - type: web
    name: text-editor-pwa
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    regions:
      - oregon
      - frankfurt
